# Generated by Django 2.1.3 on 2018-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(default='')),
                ('amount_of_places', models.IntegerField(default=4)),
                ('color', models.TextField(default='white')),
            ],
        ),
    ]
