# Generated by Django 2.1.3 on 2018-11-26 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('model', models.TextField(default='')),
                ('amount_of_places', models.IntegerField(default=4)),
                ('color', models.TextField(default='white')),
                ('car_plate', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
                ('color', models.TextField(default='white')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('charge_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 26, 9, 58, 11, 319281))),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('uid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('amount_of_available_sockets', models.IntegerField(default=0)),
                ('gps_location', models.TextField(default='')),
                ('size_of_plug', models.TextField(default='')),
                ('shape_of_plug', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(to='core.Car')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField(default=datetime.datetime(2018, 11, 26, 9, 58, 11, 319712))),
                ('time_end', models.DateTimeField(default=datetime.datetime(2018, 11, 26, 9, 58, 11, 319727))),
                ('location_begin', models.TextField(default='')),
                ('location_end', models.TextField(default='')),
                ('location_car', models.TextField(default='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_payment', models.DateTimeField(default=datetime.datetime(2018, 11, 26, 9, 58, 11, 320142))),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_providing', models.DateTimeField(default=datetime.datetime(2018, 11, 26, 9, 58, 11, 320611))),
                ('price', models.IntegerField(default=0)),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CarParts')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidingManager',
            fields=[
                ('company_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
                ('name_of_the_provider', models.TextField(default='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePark',
            fields=[
                ('vid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('location', models.TextField(default='')),
                ('amount_of_cars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshopid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='providingmanager',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='providedpart',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='operator',
            name='parks',
            field=models.ManyToManyField(to='core.VehiclePark'),
        ),
        migrations.AddField(
            model_name='customer',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Operator'),
        ),
        migrations.AddField(
            model_name='charge',
            name='charging_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ChargingStation'),
        ),
        migrations.AddField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleEngineer'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='car',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleEngineer'),
        ),
        migrations.AddField(
            model_name='car',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehiclePark'),
        ),
    ]
