# Generated by Django 2.1.3 on 2018-11-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.TextField(default='')),
                ('amount_of_places', models.IntegerField(default=4)),
                ('color', models.TextField(default='white')),
            ],
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
                ('car_model', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
                ('color', models.TextField(default='white')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('amount_of_available_sockets', models.IntegerField(default=0)),
                ('gps_location', models.TextField(default='')),
                ('size_of_plug', models.TextField(default='')),
                ('shape_of_plug', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(to='core.Car')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidngManager',
            fields=[
                ('companyid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
                ('name_of_the_provider', models.TextField(default='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePark',
            fields=[
                ('vid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.TextField(default='')),
                ('amount_of_cars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshopid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='providngmanager',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='operator',
            name='parks',
            field=models.ManyToManyField(to='core.VehiclePark'),
        ),
        migrations.AddField(
            model_name='customer',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Operator'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleEngineer'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='car',
            name='charging_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ChargingStation'),
        ),
        migrations.AddField(
            model_name='car',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleEngineer'),
        ),
        migrations.AddField(
            model_name='car',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehiclePark'),
        ),
    ]
