# Generated by Django 2.1.3 on 2018-11-22 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField(default=datetime.datetime(2018, 11, 22, 15, 59, 48, 27965))),
                ('time_end', models.DateTimeField(default=datetime.datetime(2018, 11, 22, 15, 59, 48, 27983))),
                ('location_begin', models.TextField(default='')),
                ('location_end', models.TextField(default='')),
                ('location_car', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_payment', models.DateTimeField(default=datetime.datetime(2018, 11, 22, 15, 59, 48, 28421))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_providing', models.DateTimeField(default=datetime.datetime(2018, 11, 22, 15, 59, 48, 28849))),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidingManager',
            fields=[
                ('company_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('country', models.TextField(default='')),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.TextField(default='')),
                ('name_of_the_provider', models.TextField(default='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='providngmanager',
            name='info',
        ),
        migrations.RemoveField(
            model_name='providngmanager',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='carparts',
            name='car_model',
        ),
        migrations.AddField(
            model_name='carparts',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 15, 59, 48, 27575)),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiclepark',
            name='vid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshopid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProvidngManager',
        ),
        migrations.AddField(
            model_name='providingmanager',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='providedpart',
            name='car_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CarParts'),
        ),
        migrations.AddField(
            model_name='providedpart',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
    ]
