# Generated by Django 2.1.3 on 2018-11-23 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181122_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 47, 12, 848024)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 47, 12, 848464)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 47, 12, 848482)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 47, 12, 849027)),
        ),
        migrations.AlterField(
            model_name='providedpart',
            name='time_of_providing',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 47, 12, 849422)),
        ),
    ]
