# Generated by Django 2.1.3 on 2018-11-23 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 5, 56, 905459)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 5, 56, 905861)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 5, 56, 905878)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 5, 56, 906372)),
        ),
        migrations.AlterField(
            model_name='providedpart',
            name='time_of_providing',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 5, 56, 906735)),
        ),
    ]
