# Generated by Django 2.1.3 on 2018-11-23 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181123_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 38, 26, 786574)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 38, 26, 786962)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 38, 26, 786978)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 38, 26, 787480)),
        ),
        migrations.AlterField(
            model_name='providedpart',
            name='time_of_providing',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 38, 26, 787852)),
        ),
    ]
