# Generated by Django 2.1.3 on 2018-11-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181123_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 53, 28, 922260)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 53, 28, 922658)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 53, 28, 922743)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 53, 28, 923165)),
        ),
        migrations.AlterField(
            model_name='providedpart',
            name='time_of_providing',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 53, 28, 923547)),
        ),
    ]
