# Generated by Django 2.1.3 on 2018-11-26 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181126_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car',
        ),
        migrations.AddField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 8, 59, 13, 69973)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 8, 59, 13, 70481)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 8, 59, 13, 70498)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 8, 59, 13, 70930)),
        ),
        migrations.AlterField(
            model_name='providedpart',
            name='time_of_providing',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 8, 59, 13, 71301)),
        ),
    ]
